ELECTINFO = [
# electorate name, lat, lon, current party, incumbent
["Albert Park","Labor","Mr Martin Peter Foley"],
["Altona","Labor","Jill Hennessy"],
["Bass","Liberal","Hon Kenneth Maurice Smith"],
["Bayswater","Liberal","Hon Heidi Victoria"],
["Bellarine","Labor","Hon Lisa Neville"],
["Benambra","Liberal","Mr William John Tilley"],
["Bendigo East","Labor","Hon Jacinta Marie Allan"],
["Bendigo West","Labor","Ms Janice Maree Edwards"],
["Bentleigh","Liberal","Ms Elizabeth Eileen Miller"],
["Box Hill","Liberal","Hon Robert William Clark"],
["Brighton","Liberal","Hon Louise Asher"],
["Broadmeadows","Labor","Frank McGuire"],
["Brunswick","Labor","Ms Jane Furneaux Garrett"],
["Bulleen","Liberal","Hon Nicholas Kotsiras"],
["Bundoora","Labor","Mr Colin William Brooks"],
["Buninyong","Labor","null"],
["Burwood","Liberal","Mr Graham Travis Watt"],
["Carrum","Liberal","Mrs Donna Jane Bauer"],
["Caulfield","Liberal","Mr David James Southwick"],
["Clarinda","Labor","null"],
["Cranbourne","Labor","Mr Jude Perera"],
["Croydon","Liberal","null"],
["Dandenong","Labor","Hon John Pandazopoulos"],
["Eildon","Liberal","null"],
["Eltham","Labor","Mr Steven RLaborh Herbert"],
["Essendon","Labor","Hon Justin Mark Madden"],
["Euroa","Nationals","null"],
["Evelyn","Liberal","Ms Christine Fyffe"],
["Ferntree Gully","Liberal","Hon Nicholas Wakeling"],
["Footscray","Labor","Hon Marsha Rose Thomson"],
["Forest Hill","Liberal","Mr Neil Andrew Warwick Angus"],
["Frankston","Independent","Mr Geoffrey Page Shaw"],
["Geelong","Labor","Mr Ian Douglas Trezise"],
["Gembrook","Liberal","Mr Bradley William Battin"],
["Gippsland East","Nationals","Hon Timothy Owen Bull"],
["Gippsland South","Nationals","Hon Peter Julian Ryan"],
["Hastings","Liberal","Mr Neale Ronald Burgess"],
["Hawthorn","Liberal","Hon Edward Norman Baillieu"],
["Ivanhoe","Labor","Mr Anthony Richard Carbines"],
["Kew","Liberal","Hon Andrew John McIntosh"],
["Keysborough","Labor","null"],
["Kororoit","Labor","Ms Marlene Kairouz"],
["Lara","Labor","Mr John Hamdi Eren"],
["Lowan","Nationals","Hon Hugh Francis Delahunty"],
["Macedon","Labor","Ms Joanne Therese Duncan"],
["Malvern","Liberal","Hon Michael Anthony O'Brien"],
["Melbourne","Labor","Ms Jennifer Kanis"],
["Melton","Labor","Mr DoNationalso Antonio Nardella"],
["Mildura","Nationals","Mr Peter Laurence Crisp"],
["Mill Park","Labor","Ms Liliana D'Ambrosio"],
["Monbulk","Liberal","Mr James Anthony Merlino"],
["Mordialloc","Liberal","Lorraine Joan Wreford"],
["Mornington","Liberal","Mr David Charles Morris"],
["Morwell","Nationals","Hon Russell John Northe"],
["Mount Waverley","Liberal","Mr Michael Xavier Charles Gidley"],
["Mulgrave","Labor","Hon Daniel Michael Andrews"],
["Murray Plains","Nationals","null"],
["Narracan","Liberal","Mr Gary John Blackwood"],
["Narre Warren North","Labor","Mr Luke Anthony Donnellan"],
["Narre Warren South","Labor","Ms Judith Ann Graley"],
["Nepean","Liberal","Hon Martin Francis Dixon"],
["Niddrie","Labor","Mr Benjamin Alan Carroll"],
["Northcote","Labor","Ms Fiona Catherine Alison Richardson"],
["Oakleigh","Labor","Ms Ann Patricia Barker"],
["Ovens Valley","Nationals","null"],
["Pascoe Vale","Labor","Hon Christine Mary Campbell"],
["Polwarth","Liberal","Hon Terence Wynn Mulder"],
["Prahran","Liberal","Mr Clement Arundel Newton-Brown"],
["Preston","Labor","Mr Robin David Scott"],
["Richmond","Labor","Hon Richard William Wynne"],
["Ringwood","Liberal","null"],
["Ripon","Liberal","Mr Jochen Helper"],
["Rowville","Liberal","null"],
["Sandringham","Liberal","Mr Murray Hamilton Thompson"],
["Shepparton","Nationals","Hon Elizabeth Powell"],
["South Barwon","Liberal","Mr Andrew Katos"],
["South-West Coast","Liberal","Dr Hon Denis Vincent Napthine"],
["St Albans","Labor","null"],
["Sunbury","Labor","null"],
["Sydenham","Labor","null"],
["Tarneit","Labor","Mr Timothy Hugh Pallas"],
["Thomastown","Labor","Ms Bronwyn Halfpenny"],
["Warrandyte","Liberal","Hon Ryan James Smith"],
["Wendouree","Liberal","null"],
["Werribee","Labor","null"],
["Williamstown","Labor","Mr Wade Noonan"],
["Yan Yean","Liberal","Ms Danielle Green"],
["Yuroke","Labor","Ms Elizabeth Jean Beattie"]
]
